language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target boost_test_version
- cmake --build . --target Otus_1
- ./Otus_1
- ./boost_test_version
- cmake --build . --target package
- ls
deploy:
 provider: script
 skip_cleanup: true																			 
 script:
 - curl -T OtusHomework_1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -upavelkaryukov:$BINTRAY_API_KEY "https://api.bintray.com/content/karyukov/otus/otus_1/$TRAVIS_BUILD_NUMBER/OtusHomework_1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"